services:
  # PostgreSQL pour les données métier
  postgres:
    image: postgres:15-alpine
    container_name: ft-postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: francetravail_jobs
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ft_user -d francetravail_jobs"]
      interval: 10s
      timeout: 5s
      retries: 5

 
  # FastAPI
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: ft-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: postgres
      API_HOST: 0.0.0.0
      API_PORT: 8000
      PYTHONPATH: /app/src
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ft-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Streamlit
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    container_name: ft-streamlit
    depends_on:
      - api
    env_file:
      - ../.env
    environment:
      STREAMLIT_API_URL: http://api:8000
      PYTHONPATH: /app/src
    ports:
      - "8501:8501"
    volumes:
      - ../src:/app/src
    command: streamlit run src/streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - ft-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ft-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ft-network
  
  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ft-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    networks:
      - ft-network


networks:
  ft-network:
    driver: bridge

volumes:
  postgres_data: